---
# -- (Optional) When using a custom network
# networks:
#   your-traefik-network:
#     external: true

#store SSL certs locally
#volumes:
#  traefik-ssl-certs:
#    driver: local

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      - 8080:8080
    volumes:
      - ./config:/etc/traefik/
      #- traefik-ssl-certs:/ssl-certs
      #- ./certs:/etc/traefik/certs/
      #- ./certs/acme.json:/etc/traefik/certs/acme.json
      #- ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # -- (Optional) When using Cloudflare as Cert Resolver
    # environment:
    #   - CF_DNS_API_TOKEN=your-cloudflare-api-token
    # -- (Optional) When using a custom network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=traefik"
      - "traefik.http.routers.traefik.rule=Host(`oracle.vives.live`)"
      - "traefik.http.routers.traefik.tls.certresolver=staging"
      - "traefik.http.routers.traefik.tls.domains[0].main=oracle.vives.live"
    restart: unless-stopped
    networks:
      - traefik-public

  nginx:
    image: nginx:latest
    container_name: oracleapp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oracleapp.entrypoints=websecure"
      - "traefik.http.routers.oracleapp.rule=Host(`nginx.viveslabs.duckdns.org`)"
      - "traefik.http.routers.oracleapp.tls.certresolver=staging"
      - "traefik.http.routers.oracleapp.tls.domains[0].main=nginx.viveslabs.duckdns.org"
    restart: unless-stopped
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
#networks:
#  traefik_default:
#    external: true
